name: Release Binary Package
on:
  release:
    types: [created]
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Mount caches
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: caches-${{ runner.os }}-release
      - name: Setup bazelisk for Bazel builds
        uses: holvonix-open/setup-bazelisk@v0.6.1
      - name: Create release artifact
        run: bazel build //:rules_kotlin_release
      - name: Upload release artifact
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bazel-bin/rules_kotlin_release.*
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
